spring:
  profiles:
    active: dev
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

#freemarker模板配置
  freemarker:
    suffix: .ftl
    cache: false
    charset: UTF-8
    contentType: text/html
    requestContextAttribute: ctx
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    settings:
      defaultEncoding: UTF-8
      url_escaping_charset: UTF-8
      locale: zh_CN
  http:
    multipart:
      max-file-size: -1
      max-request-size: -1
    activiti:
      check-process-definitions: false

server:
  session:
    timeout: 3600

---
#环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://47.100.34.166:3307/activiti6?useUnicode=true&useSSL=false&amp;characterEncoding=utf8&allowMultiQueries=true
    username: uipath
    password: 123456789A

#server:
#  port: 8899
#
#https端口号.
server.port: 8899
#证书的路径.
server.ssl.key-store: classpath:keystore1.p12
#证书密码，请修改为您自己证书的密码.
server.ssl.key-store-password: 123456
#秘钥库类型
server.ssl.keyStoreType: PKCS12
#证书别名
server.ssl.keyAlias: tomcat

